apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  annotations:
    github.com/project-slug: minkzaw/my-demo-app
    roadie-backstage-pull-requests/default-filter: is:open is:pr author:app%2Fmy-bot
spec:
  type: service
  owner: user:default/guest
  lifecycle: experimental
  dependsOn: 
    - "resource:my-demo-app-ec2"
